### ISSUE TITLE
cant start pool

### ISSUE THREAD

**Issue by pfreak2000** [Groestlcoin/p2pool-grs#8]
no module names groestlcoin_hash

But i installed the subsidy

C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-grs\groestlcoin-subsidy-python>python setup.py install
running install
running build
running build_ext
running install_lib
running install_egg_info
Removing C:\Python27\Lib\site-packages\groestlcoin_subsidy-1.0-py2.7.egg-info
Writing C:\Python27\Lib\site-packages\groestlcoin_subsidy-1.0-py2.7.egg-info

**Comment by gruve-p** [comment]
https://github.com/aleks-azen/p2pool-grs-setupguide#compile-the-groestlcoin-hash-module-optional

**Comment by pfreak2000** [comment]
i was installing the module but it dont work.

this is my pool site http://p2p-multipool.eu  i run many p2pools, only the groestlecoin pool dont run

run_p2pool.py: error: error parsing address: ImportError('No module named groestlcoin_hash',)

**Comment by gruve-p** [comment]
This repo will deprecate soon. Please help testing with our new repo: https://github.com/Groestlcoin/p2pool/tree/groestlize

**Comment by gruve-p** [comment]
This repo has been deprecated.
New repo: https://github.com/Groestlcoin/p2pool/
